### ISSUE TITLE
Development mode

### ISSUE THREAD

**Issue by marvinroger** [eugeneware/wiring-pi#12]
Hi,

Thanks for this amazing lib! However, I have a feature request that would greatly improve development.
It would be great if the lib could detect if it's running on a RPi or not. If it is, then it builds normally using node-gyp. If it doesn't, it could fallback into development mode, which can be as simple as logging what method is called.

This would allow a RPi specific app to be runnable in another environment.

A solution may be:

* In install.sh
    * Check the existence of /opt/vc/bin/raspivid that seems to be present only on RPi
        * If it exists, build wiring-pi
        * Else, `touch DEVELOPMENT`
* Wrap the current code and check if DEVELOPMENT exists
    * If it exists, run into development mode
    * Else, run normally

I think this should be pretty easy to implement... However, I can't do a PR as I don't feel confident about native extensions. ;)

**Comment by nekuz0r** [comment]
Any news about this requested feature ?

**Comment by marvinroger** [comment]
Sorry, I haven't seen your update.

I did not think about the methods returning value... One way could have been to let the developer set fake data. Imagine the dev creates an app logging temperature coming from a light sensor (no analog input on RPi, simplified for the example). Then he would do something like:

```javascript
var wpi = require('wiring-pi');

if (wpi.mode == 'development') {
  setInterval(function() {
    var analogLight = Math.floor(Math.random()*(255+1)); // Generate random value between 0 and 255
    setFakeAnalogRead(0, analogLight);
  }, 1 * 1000);
}
```

This way, every second the pin value would change, just like a real sensor would do. This would work for the core functions like digitalRead and analogRead, but obviously not for things like SPI or I2C.

**Comment by marvinroger** [comment]
But I don't think this is something this lib should handle. This is basically mocking, libs like [mockery](https://github.com/mfncooper/mockery) can handle that.
The only problem as of now to use mockery is that wiring-pi don't build on non-RPi env.

Here is an updated solution:

* In install.sh
    * Check the existence of /opt/vc/bin/raspivid that seems to be present only on RPi
        * If it exists, build wiring-pi
        * Else, `touch DEVELOPMENT`
* Wrap the current code and check if DEVELOPMENT exists
    * If it doesn't exist, run normally (export native code)
    * Else, export ghost methods that do nothing, except maybe log a "wiring-pi: not called on a RPi"
* In doc
    * Write a litle text about mocking functions

I think this would be much cleaner.

**Comment by nekuz0r** [comment]
An idea came to my mind right now, maybe we can consider creating a different project written in pure js that mock wiring-pi.
