### ISSUE TITLE
Does not work with Raspberry Pi 2

### ISSUE THREAD

**Issue by Achronite** [eugeneware/wiring-pi#19]
Can you please update the package to include gordon's new libraries for WiringPi?  I believe you need at least version 24 to enable this to work correctly with the new raspberry Pi 2.

**Comment by nekuz0r** [comment]
It's in progress, rpi 2 support will be available with v2.1.0

**Comment by Achronite** [comment]
Excellent - Thanks for the quick reply.

**Comment by nekuz0r** [comment]
As you can see here : https://github.com/nekuz0r/wiringpi/tree/incoming-v2.25
A new version of the custom libWiringPi will be released in parallel of the node wiring-pi v2.1.0 module

**Comment by nitram509** [comment]
I've did a little monkey patching and crafted a wiring-pi fork working on Raspberry Pi 2 with the latest wiringPi code.

This may give @nekuz0r a starting point for migration or helps other people (like @Achronite) as an interim solution, until v.2.1.0 is available.

See my fork for details:
https://github.com/nitram509/wiring-pi
