### ISSUE TITLE
Is working at B+ and Raspberry Pi B 2

### ISSUE THREAD

**Issue by rippertnt** [eugeneware/wiring-pi#25]
Hello!
I use your works very well to my raspberry pis..
But unfortunately, B+ and B 's additional gpios are not working at wiring-pi.
I think this project are referencing old wiringpi (Native C library).
Could you have any plan to upgrade this project to use B+ and B 2?

**Comment by nekuz0r** [comment]
Hi,

The release of the next version 2.1.0 is scheduled by the end of the week.
See pull request #20
