### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by icode** [eugeneware/wiring-pi#28]
pi@raspberrypi ~/autocar $ npm rebuild

> wiring-pi@2.0.0 install /home/pi/autocar/node_modules/wiring-pi
> /bin/bash ./install.sh

Cloning libWiringPi ... done.
patching file ./wiringpi/devLib/Makefile
patching file ./wiringpi/gpio/Makefile
Making libWiringPi ... done.
Making devLib ...done.
Unistalling gpio utility ... done.
Making gpio utility ... done.
Installing gpio utility ... done.
Making wiring-pi ... make: Entering directory '/home/pi/autocar/node_modules/wiring-pi/build'
  CXX(target) Release/obj.target/wiringPi/src/addon.o
../src/addon.cc: In function ‘void throw_error(const char*, ...)’:
../src/addon.cc:30:3: error: ‘ThrowException’ is not a member of ‘v8’
../src/addon.cc:30:43: error: ‘New’ is not a member of ‘v8::String’
wiringPi.target.mk:128: recipe for target 'Release/obj.target/wiringPi/src/addon.o' failed
make: *** [Release/obj.target/wiringPi/src/addon.o] Error 1
make: Leaving directory '/home/pi/autocar/node_modules/wiring-pi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/autocar/node_modules/wiring-pi
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
done.
Enjoy !
wiring-pi@2.0.0 /home/pi/autocar/node_modules/wiring-pi
async@1.4.0 /home/pi/autocar/node_modules/async

**Comment by nekuz0r** [comment]
Hi, did you tried the last version 2.1.0 ?
