### ISSUE TITLE
ERR : wiringPiSetup: Must be root. (Did you forget sudo?)

### ISSUE THREAD

**Issue by trojanspike** [eugeneware/wiring-pi#32]
Isn't it best practice to not use root ? User permissions should be enough , also I'm using nvm Node Version Manager , I don't give root node software.

**Comment by nekuz0r** [comment]
Hi there is no issue here,
root is required by most of working mode (see setup documentation).
If you don't want to give root access to your application use mode sys.

**Comment by trojanspike** [comment]
sys does nothing to help - I guess I'l have to use sudo until I get a better solution .
My temp solution for anyone else having an issue when also using nodeVerionManager
```bash
#!/usr/bin/env bash

sudo $(which node) $@
```
