### ISSUE TITLE
sn3218 extension not available

### ISSUE THREAD

**Issue by paulrosbif** [eugeneware/wiring-pi#42]
I'm using node v5.11.0 on a Raspberry PI 3, with gpio v2.32.  I've added the wiring-pi via npm and while I can use the basic functions (for example wpi.wiringPiSetup()) when I try to run a simple test:
`var wpi = require('wiring-pi');
var basePin = 64;
wpi.wiringPiSetup();
wpi.sn3218Setup(basePin);
wpi.analogWrite(1,255);
console.log("Pin should be on");`
I get `TypeError: wpi.sn3218Setup is not a function`.  Is there some additional setup I'm missing for the extension?

**Comment by nekuz0r** [comment]
Hi, just checked this out, and looks like some extensions are not loaded in https://github.com/eugeneware/wiring-pi/blob/master/src/extensions/extensions.cc

**Comment by NoHomey** [comment]
Hey @nekuz0r  I've just created a PR #49 to fix this issue. Could you review it?

**Comment by paulrosbif** [comment]
Excellent! I'll go try it
Paul
