### ISSUE TITLE
How to release a wiringPiI2CSetup() file descriptor 

### ISSUE THREAD

**Issue by nkolban** [eugeneware/wiring-pi#43]
If I call wiringPiI2CSetup() I am returned an open file descriptor.  What is the correct way to dispose of this if I no longer need the resource?

**Comment by nekuz0r** [comment]
Good catch sir !
There is indeed a missing close function, the native wiring pi library does not provide any close function because it expects you to call `close` since it's open with `open`.
Will add a dispose function for I2C and any other resources opening a file descriptor

**Comment by NoHomey** [comment]
@nekuz0r  I've created #50 with which I added individual closing functions for `SPI` and `I2C` interfaces. Could you review it?
