### ISSUE TITLE
[2.1.1] Officially Release 2.1.1

### ISSUE THREAD

**Issue by NoHomey** [eugeneware/wiring-pi#51]
Currently `wiring-pi` latest versions at `npm` and here in `github releases` both point to `2.1.1` but in the [Changelog](https://github.com/eugeneware/wiring-pi/blob/master/CHANGELOG.md#v211-not-released-yet) `2.1.1` is marked as `not released yet`... So what stops `2.1.1` to be officially released?

**Comment by nekuz0r** [comment]
I think we simply forgot to update the changelog
